-- ============================================================
-- Outlaw Events — consolidated clean schema
-- ============================================================

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER LANGUAGE plpgsql SET search_path = public AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END; $$;

-- ---------- content blocks ----------
CREATE TABLE public.blocks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  section text NOT NULL DEFAULT 'events',
  slot int NOT NULL,
  content text NOT NULL DEFAULT '',
  image_url text,
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX blocks_section_slot_key ON public.blocks (section, slot);
GRANT SELECT ON public.blocks TO anon, authenticated;
GRANT ALL ON public.blocks TO service_role;
ALTER TABLE public.blocks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read blocks" ON public.blocks FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE public.block_images (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  block_id uuid NOT NULL REFERENCES public.blocks(id) ON DELETE CASCADE,
  path text NOT NULL,
  position integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX block_images_block_id_position_idx ON public.block_images (block_id, position);
GRANT SELECT ON public.block_images TO anon, authenticated;
GRANT ALL ON public.block_images TO service_role;
ALTER TABLE public.block_images ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read block_images" ON public.block_images FOR SELECT TO anon, authenticated USING (true);
CREATE TRIGGER update_block_images_updated_at BEFORE UPDATE ON public.block_images
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TABLE public.site_settings (
  id boolean PRIMARY KEY DEFAULT true CHECK (id),
  view_only boolean NOT NULL DEFAULT false,
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.site_settings TO anon, authenticated;
GRANT ALL ON public.site_settings TO service_role;
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read settings" ON public.site_settings FOR SELECT TO anon, authenticated USING (true);
INSERT INTO public.site_settings (id, view_only) VALUES (true, false);

-- ---------- visitors + secret gate ----------
CREATE TABLE public.visitors (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  token text NOT NULL UNIQUE,
  number bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz NOT NULL DEFAULT now(),
  label text
);
GRANT ALL ON public.visitors TO service_role;
ALTER TABLE public.visitors ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.admin_credential (
  id boolean PRIMARY KEY DEFAULT true CHECK (id),
  code_hash text NOT NULL,
  image_hash text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT ALL ON public.admin_credential TO service_role;
ALTER TABLE public.admin_credential ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER update_admin_credential_updated_at BEFORE UPDATE ON public.admin_credential
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TABLE public.gate_verifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  visitor_id uuid NOT NULL REFERENCES public.visitors(id) ON DELETE CASCADE,
  visitor_number bigint NOT NULL,
  session_binding_hash text NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','verified','failed','revoked')),
  entered_at timestamptz NOT NULL DEFAULT now(),
  attempted_at timestamptz,
  verified_at timestamptz,
  access_token_hash text,
  access_expires_at timestamptz,
  last_seen_at timestamptz
);
GRANT ALL ON public.gate_verifications TO service_role;
ALTER TABLE public.gate_verifications ENABLE ROW LEVEL SECURITY;
CREATE INDEX gate_verifications_entered_at_idx ON public.gate_verifications (entered_at DESC);
CREATE INDEX gate_verifications_visitor_id_idx ON public.gate_verifications (visitor_id);
CREATE INDEX gate_verifications_status_idx ON public.gate_verifications (status, entered_at DESC);
CREATE INDEX gate_verifications_access_token_hash_idx ON public.gate_verifications (access_token_hash);

-- ---------- suggestions ----------
CREATE TABLE public.suggestions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  title text NOT NULL,
  body text NOT NULL,
  images text[] NOT NULL DEFAULT '{}',
  visitor_number bigint,
  status text NOT NULL DEFAULT 'pending',
  review_note text,
  reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT ALL ON public.suggestions TO service_role;
ALTER TABLE public.suggestions ENABLE ROW LEVEL SECURITY;
CREATE INDEX suggestions_status_created_idx ON public.suggestions (status, created_at DESC);
CREATE TRIGGER update_suggestions_updated_at BEFORE UPDATE ON public.suggestions
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ---------- edit requests ----------
CREATE TABLE public.edit_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  section text NOT NULL,
  visitor_number bigint,
  note text,
  status text NOT NULL DEFAULT 'pending',
  entries jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  reviewed_at timestamptz
);
GRANT ALL ON public.edit_requests TO service_role;
ALTER TABLE public.edit_requests ENABLE ROW LEVEL SECURITY;
CREATE INDEX edit_requests_status_created_idx ON public.edit_requests (status, created_at DESC);

-- ---------- gate RPCs (SECURITY DEFINER, service_role only) ----------
CREATE OR REPLACE FUNCTION public.gate_ensure_visitor(p_token text DEFAULT NULL)
RETURNS TABLE(token text, number bigint, label text)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE
  v public.visitors%ROWTYPE;
  clean_token text := nullif(left(trim(coalesce(p_token, '')), 200), '');
BEGIN
  IF clean_token IS NOT NULL THEN
    SELECT * INTO v FROM public.visitors WHERE visitors.token = clean_token;
  END IF;
  IF v.id IS NULL THEN
    INSERT INTO public.visitors(token) VALUES (gen_random_uuid()::text) RETURNING * INTO v;
    UPDATE public.visitors SET label = 'OUTLAW-VISITOR-' || v.number::text WHERE id = v.id RETURNING * INTO v;
  END IF;
  RETURN QUERY SELECT v.token, v.number, coalesce(v.label, 'OUTLAW-VISITOR-' || v.number::text);
END; $$;
REVOKE ALL ON FUNCTION public.gate_ensure_visitor(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.gate_ensure_visitor(text) TO service_role;

CREATE OR REPLACE FUNCTION public.gate_admin_status()
RETURNS boolean LANGUAGE sql SECURITY DEFINER SET search_path = public, pg_temp
AS $$ SELECT EXISTS (SELECT 1 FROM public.admin_credential) $$;
REVOKE ALL ON FUNCTION public.gate_admin_status() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.gate_admin_status() TO service_role;

CREATE OR REPLACE FUNCTION public.gate_begin_verification(p_token text, p_binding_hash text)
RETURNS TABLE(verification_id uuid, visitor_id uuid, visitor_number bigint, visitor_label text, initialized boolean)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE v public.visitors%ROWTYPE; verification uuid;
BEGIN
  SELECT * INTO v FROM public.visitors WHERE token = left(trim(coalesce(p_token, '')), 200);
  IF v.id IS NULL THEN RAISE EXCEPTION 'visitor_not_found'; END IF;
  INSERT INTO public.gate_verifications(visitor_id, visitor_number, session_binding_hash, status)
  VALUES (v.id, v.number, p_binding_hash, 'pending') RETURNING id INTO verification;
  RETURN QUERY SELECT verification, v.id, v.number,
    coalesce(v.label, 'OUTLAW-VISITOR-' || v.number::text),
    EXISTS (SELECT 1 FROM public.admin_credential);
END; $$;
REVOKE ALL ON FUNCTION public.gate_begin_verification(text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.gate_begin_verification(text, text) TO service_role;

CREATE OR REPLACE FUNCTION public.gate_verify(
  p_visitor_token text, p_code_hash text, p_image_hash text,
  p_access_token_hash text, p_access_expires_at timestamptz)
RETURNS TABLE(ok boolean, created boolean, verification_id uuid, visitor_number bigint, visitor_label text)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE
  v public.visitors%ROWTYPE; verification uuid;
  credential public.admin_credential%ROWTYPE; was_created boolean := false;
BEGIN
  SELECT * INTO v FROM public.visitors WHERE token = left(trim(coalesce(p_visitor_token, '')), 200);
  IF v.id IS NULL THEN RETURN QUERY SELECT false, false, NULL::uuid, NULL::bigint, NULL::text; RETURN; END IF;

  SELECT id INTO verification FROM public.gate_verifications
  WHERE visitor_id = v.id AND status = 'pending' ORDER BY entered_at DESC LIMIT 1;
  IF verification IS NULL THEN RETURN QUERY SELECT false, false, NULL::uuid, v.number, v.label; RETURN; END IF;

  PERFORM pg_advisory_xact_lock(7158201);
  SELECT * INTO credential FROM public.admin_credential WHERE id = true;
  IF credential.id IS NULL THEN
    INSERT INTO public.admin_credential(id, code_hash, image_hash) VALUES (true, p_code_hash, p_image_hash);
    was_created := true;
  ELSIF credential.code_hash <> p_code_hash OR credential.image_hash <> p_image_hash THEN
    UPDATE public.gate_verifications SET status = 'failed', attempted_at = now() WHERE id = verification;
    RETURN QUERY SELECT false, false, verification, v.number, coalesce(v.label, 'OUTLAW-VISITOR-' || v.number::text);
    RETURN;
  END IF;

  UPDATE public.gate_verifications SET
    status = 'verified', attempted_at = now(), verified_at = now(), last_seen_at = now(),
    access_token_hash = p_access_token_hash, access_expires_at = p_access_expires_at
  WHERE id = verification;

  RETURN QUERY SELECT true, was_created, verification, v.number,
    coalesce(v.label, 'OUTLAW-VISITOR-' || v.number::text);
END; $$;
REVOKE ALL ON FUNCTION public.gate_verify(text, text, text, text, timestamptz) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.gate_verify(text, text, text, text, timestamptz) TO service_role;

CREATE OR REPLACE FUNCTION public.gate_revoke(p_access_token_hash text)
RETURNS void LANGUAGE sql SECURITY DEFINER SET search_path = public, pg_temp AS $$
  UPDATE public.gate_verifications SET status = 'revoked', access_token_hash = NULL, access_expires_at = NULL
  WHERE access_token_hash = p_access_token_hash $$;
REVOKE ALL ON FUNCTION public.gate_revoke(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.gate_revoke(text) TO service_role;

CREATE OR REPLACE FUNCTION public.gate_require_admin(p_access_token_hash text, p_visitor_token text DEFAULT NULL)
RETURNS TABLE(admin boolean, visitor_number bigint)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE verification public.gate_verifications%ROWTYPE; supplied_visitor uuid;
BEGIN
  SELECT * INTO verification FROM public.gate_verifications
  WHERE access_token_hash = p_access_token_hash AND status = 'verified' AND access_expires_at > now();
  IF verification.id IS NULL THEN RETURN QUERY SELECT false, NULL::bigint; RETURN; END IF;
  IF nullif(trim(coalesce(p_visitor_token, '')), '') IS NOT NULL THEN
    SELECT id INTO supplied_visitor FROM public.visitors WHERE token = left(trim(p_visitor_token), 200);
    IF supplied_visitor IS NULL OR supplied_visitor <> verification.visitor_id THEN
      RETURN QUERY SELECT false, NULL::bigint; RETURN;
    END IF;
  END IF;
  UPDATE public.gate_verifications SET last_seen_at = now() WHERE id = verification.id;
  RETURN QUERY SELECT true, verification.visitor_number;
END; $$;
REVOKE ALL ON FUNCTION public.gate_require_admin(text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.gate_require_admin(text, text) TO service_role;

CREATE OR REPLACE FUNCTION public.gate_session_admin(p_verification_id uuid, p_visitor_id uuid, p_binding_hash text)
RETURNS TABLE(admin boolean, visitor_number bigint)
LANGUAGE sql SECURITY DEFINER SET search_path = public, pg_temp AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.gate_verifications
    WHERE id = p_verification_id AND visitor_id = p_visitor_id
      AND session_binding_hash = p_binding_hash AND status = 'verified' AND access_expires_at > now()
  ),
  (SELECT gv.visitor_number FROM public.gate_verifications gv
    WHERE gv.id = p_verification_id AND gv.visitor_id = p_visitor_id LIMIT 1)
$$;
REVOKE ALL ON FUNCTION public.gate_session_admin(uuid, uuid, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.gate_session_admin(uuid, uuid, text) TO service_role;

-- ---------- realtime ----------
ALTER TABLE public.blocks REPLICA IDENTITY FULL;
ALTER TABLE public.block_images REPLICA IDENTITY FULL;
ALTER TABLE public.site_settings REPLICA IDENTITY FULL;
ALTER PUBLICATION supabase_realtime ADD TABLE public.blocks;
ALTER PUBLICATION supabase_realtime ADD TABLE public.block_images;
ALTER PUBLICATION supabase_realtime ADD TABLE public.site_settings;

-- TEMP: one-time content import window (removed in the next migration)
CREATE POLICY "temp import blocks" ON public.blocks FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "temp import block_images" ON public.block_images FOR INSERT TO anon WITH CHECK (true);
GRANT INSERT ON public.blocks TO anon;
GRANT INSERT ON public.block_images TO anon;