// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'
import { getBrowserSupabaseConfigSync } from './runtime-config'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    // The first browser request may be the public runtime-config server function.
    // Do not initialize Supabase until that request has supplied its URL and key;
    // otherwise the config request itself crashes before it can return the config.
    if (!getBrowserSupabaseConfigSync()) {
      return next()
    }

    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
